<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-30T23:00:27 IST" name="Suite" finished-at="2024-09-30T23:00:54 IST" duration-ms="26944">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.LoginErrorValidation()[pri:0, instance:hcyclewala.tests.ErrorValidationsTest@12591ac8]" name="LoginErrorValidation" class="hcyclewala.tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:hcyclewala.tests.SubmitOrderTest@c430e6c]" name="submitOrder" class="hcyclewala.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-09-30T23:00:27 IST" name="Error Validations Test" finished-at="2024-09-30T23:00:53 IST" duration-ms="26474">
      <class name="hcyclewala.tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:hcyclewala.tests.ErrorValidationsTest@12591ac8]" started-at="2024-09-30T23:00:27 IST" name="launchApplication" finished-at="2024-09-30T23:00:33 IST" duration-ms="6096" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:hcyclewala.tests.ErrorValidationsTest@12591ac8]" started-at="2024-09-30T23:00:33 IST" name="LoginErrorValidation" finished-at="2024-09-30T23:00:36 IST" duration-ms="3145" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at hcyclewala.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:hcyclewala.tests.ErrorValidationsTest@12591ac8]" started-at="2024-09-30T23:00:36 IST" name="tearDown" finished-at="2024-09-30T23:00:37 IST" duration-ms="561" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:hcyclewala.tests.ErrorValidationsTest@12591ac8]" started-at="2024-09-30T23:00:37 IST" name="launchApplication" finished-at="2024-09-30T23:00:41 IST" duration-ms="4508" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:hcyclewala.tests.ErrorValidationsTest@12591ac8]" started-at="2024-09-30T23:00:41 IST" name="LoginErrorValidation" finished-at="2024-09-30T23:00:42 IST" duration-ms="1067" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at hcyclewala.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:hcyclewala.tests.ErrorValidationsTest@12591ac8]" started-at="2024-09-30T23:00:42 IST" name="tearDown" finished-at="2024-09-30T23:00:43 IST" duration-ms="267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:hcyclewala.tests.ErrorValidationsTest@12591ac8]" started-at="2024-09-30T23:00:43 IST" name="launchApplication" finished-at="2024-09-30T23:00:49 IST" duration-ms="6656" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:hcyclewala.tests.ErrorValidationsTest@12591ac8]" started-at="2024-09-30T23:00:49 IST" name="ProductErrorValidation" finished-at="2024-09-30T23:00:53 IST" duration-ms="3215" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:hcyclewala.tests.ErrorValidationsTest@12591ac8]" started-at="2024-09-30T23:00:53 IST" name="tearDown" finished-at="2024-09-30T23:00:53 IST" duration-ms="658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- hcyclewala.tests.ErrorValidationsTest -->
    </test> <!-- Error Validations Test -->
    <test started-at="2024-09-30T23:00:27 IST" name="Submit Order Test" finished-at="2024-09-30T23:00:54 IST" duration-ms="26944">
      <class name="hcyclewala.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:hcyclewala.tests.SubmitOrderTest@c430e6c]" started-at="2024-09-30T23:00:27 IST" name="launchApplication" finished-at="2024-09-30T23:00:32 IST" duration-ms="5034" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:hcyclewala.tests.SubmitOrderTest@c430e6c]" started-at="2024-09-30T23:00:32 IST" name="submitOrder" data-provider="getData" finished-at="2024-09-30T23:00:40 IST" duration-ms="7758" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Hostel@1234, email=Husain@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:hcyclewala.tests.SubmitOrderTest@c430e6c]" started-at="2024-09-30T23:00:40 IST" name="tearDown" finished-at="2024-09-30T23:00:43 IST" duration-ms="3064" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:hcyclewala.tests.SubmitOrderTest@c430e6c]" started-at="2024-09-30T23:00:43 IST" name="launchApplication" finished-at="2024-09-30T23:00:48 IST" duration-ms="5092" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:hcyclewala.tests.SubmitOrderTest@c430e6c]" started-at="2024-09-30T23:00:48 IST" name="submitOrder" data-provider="getData" finished-at="2024-09-30T23:00:52 IST" duration-ms="3879" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Hostel@1234, email=Husain@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at hcyclewala.tests.SubmitOrderTest.submitOrder(SubmitOrderTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:hcyclewala.tests.SubmitOrderTest@c430e6c]" started-at="2024-09-30T23:00:52 IST" name="tearDown" finished-at="2024-09-30T23:00:54 IST" duration-ms="1588" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrdersHistory()[pri:0, instance:hcyclewala.tests.SubmitOrderTest@c430e6c]" started-at="2024-09-30T23:00:54 IST" name="OrdersHistory" finished-at="2024-09-30T23:00:54 IST" depends-on-methods="hcyclewala.tests.SubmitOrderTest.submitOrder" duration-ms="2" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method hcyclewala.tests.SubmitOrderTest.OrdersHistory() on instance hcyclewala.tests.SubmitOrderTest@c430e6c depends on not successfully finished methods 
[hcyclewala.tests.SubmitOrderTest.submitOrder() on instance hcyclewala.tests.SubmitOrderTest@c430e6c]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method hcyclewala.tests.SubmitOrderTest.OrdersHistory() on instance hcyclewala.tests.SubmitOrderTest@c430e6c depends on not successfully finished methods 
[hcyclewala.tests.SubmitOrderTest.submitOrder() on instance hcyclewala.tests.SubmitOrderTest@c430e6c]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrdersHistory -->
      </class> <!-- hcyclewala.tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
